/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackTitle: typeof import('./../src/components/Scaffold/BackTitle.vue')['default']
    ChangePasswordTemplate: typeof import('./../src/components/TheHeader/ChangePasswordTemplate.vue')['default']
    DateRange: typeof import('./../src/components/DateRange.vue')['default']
    Dialog: typeof import('./../src/components/Dialog.vue')['default']
    EChartsWrapper: typeof import('./../src/components/EChartsWrapper.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElFromItem: typeof import('element-plus/es')['ElFromItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    MoreTextTooltip: typeof import('./../src/components/MoreTextTooltip.vue')['default']
    Pagination: typeof import('./../src/components/Scaffold/Pagination.vue')['default']
    Query: typeof import('./../src/components/Scaffold/Query.vue')['default']
    QueryItem: typeof import('./../src/components/Scaffold/QueryItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scaffold: typeof import('./../src/components/Scaffold/index.vue')['default']
    ScaffoldTable: typeof import('./../src/components/Scaffold/ScaffoldTable.jsx')['default']
    SelectWithOptions: typeof import('./../src/components/SelectWithOptions.vue')['default']
    Table: typeof import('./../src/components/Scaffold/Table.vue')['default']
    Tablfffe: typeof import('./../src/components/Scaffold/Tablfffe.vue')['default']
    Temp: typeof import('./../src/components/Temp.vue')['default']
    Test: typeof import('./../src/components/Test.vue')['default']
    TheHeader: typeof import('./../src/components/TheHeader/index.vue')['default']
    TheNav: typeof import('./../src/components/TheNav.vue')['default']
    TheTest: typeof import('./../src/components/Scaffold/TheTest.jsx')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
